#!/bin/bash
intexit() {
    # Kill all subprocesses (all processes in the current process group)
    kill -HUP -$$
}

hupexit() {
    # HUP'd (probably by intexit)
    echo
    echo "Interrupted"
    exit
}

trap hupexit HUP
trap intexit INT

./node_modules/babel-cli/bin/babel-node.js --presets es2015,react,stage-2 ./src/server/server.js
