function _getBomItems(bomID){
  return {
    582 : {
      "id":582,
      "bomID":bomID,
      "partNumber":"217-3261",
      "vendor":"Vex",
      "desc":"1\/2\" Acetal Spacer - 1\/2\" Hex (10-pack)",
      "customization":"",
      "unitsNeeded":0,
      "spareUnitsNeeded":20,
      "unitsInShop":0,
      "packagePrice":4.99,
      "unitsPerPackage":10,
      "notes":"",
      "dateAdded":null,
      "dateVerified":1455803958,
      "imgPath":"\/util\/img\/img-582.jpg",
      "itemLink":"http:\/\/www.vexrobotics.com\/acetalspacers-vexpro.html",
      "ordered":0,
      "received":0,
      "receipts":null
    },
    581 : {
      "id":581,
      "bomID":bomID,
      "partNumber":"217-3259",
      "vendor":"Vex",
      "desc":"1\/4\" Acetal Spacer - 1\/2\" Hex (10-pack)",
      "customization":"",
      "unitsNeeded":0,
      "spareUnitsNeeded":30,
      "unitsInShop":0,
      "packagePrice":4.99,
      "unitsPerPackage":10,
      "notes":"",
      "dateAdded":null,
      "dateVerified":1455803959,
      "imgPath":"\/util\/img\/img-581.jpg",
      "itemLink":"http:\/\/www.vexrobotics.com\/acetalspacers-vexpro.html",
      "ordered":0,
      "received":0,
      "receipts":null
    },
    580 : {
      "id":580,
      "bomID":bomID,
      "partNumber":"217-2758",
      "vendor":"Vex",
      "desc":"1\/8\" Acetal Spacer - 1\/2\" Hex (10-pack)",
      "customization":"",
      "unitsNeeded":0,
      "spareUnitsNeeded":30,
      "unitsInShop":0,
      "packagePrice":4.99,
      "unitsPerPackage":10,
      "notes":"",
      "dateAdded":null,
      "dateVerified":1455803960,
      "imgPath":"\/util\/img\/img-580.jpg",
      "itemLink":"http:\/\/www.vexrobotics.com\/acetalspacers-vexpro.html",
      "ordered":0,
      "received":0,
      "receipts":null
    },
    579 : {
      "id":579,
      "bomID":bomID,
      "partNumber":"217-3257",
      "vendor":"Vex",
      "desc":"1\/16\" Acetal Spacer - 1\/2\" Hex (10-pack)",
      "customization":"",
      "unitsNeeded":0,
      "spareUnitsNeeded":30,
      "unitsInShop":0,
      "packagePrice":4.99,
      "unitsPerPackage":10,
      "notes":"",
      "dateAdded":null,
      "dateVerified":1455803961,
      "imgPath":"\/util\/img\/img-579.jpg",
      "itemLink":"http:\/\/www.vexrobotics.com\/acetalspacers-vexpro.html",
      "ordered":0,
      "received":0,
      "receipts":null
    },
    578 : {
      "id":578,
      "bomID":bomID,
      "partNumber":"217-3311",
      "vendor":"Vex",
      "desc":"1\/2\" OD Round Tube Axle Stock (18 inches)",
      "customization":"",
      "unitsNeeded":1,
      "spareUnitsNeeded":1,
      "unitsInShop":0,
      "packagePrice":6.99,
      "unitsPerPackage":1,
      "notes":"",
      "dateAdded":null,
      "dateVerified":1455803963,
      "imgPath":"\/util\/img\/img-578.jpg",
      "itemLink":"http:\/\/www.vexrobotics.com\/shaft-stock.html",
      "ordered":0,
      "received":0,
      "receipts":null
    },
    577 : {
      "id":577,
      "bomID":bomID,
      "partNumber":"217-2706",
      "vendor":"Vex",
      "desc":"34t Gear with 1\/2\" Hex Bore",
      "customization":"",
      "unitsNeeded":8,
      "spareUnitsNeeded":0,
      "unitsInShop":0,
      "packagePrice":8.99,
      "unitsPerPackage":1,
      "notes":"",
      "dateAdded":null,
      "dateVerified":1455803964,
      "imgPath":"\/util\/img\/img-577.jpg",
      "itemLink":"http:\/\/www.vexrobotics.com\/1-2-hex-bore.html",
      "ordered":0,
      "received":0,
      "receipts":null
    },
    576 : {
      "id":576,
      "bomID":bomID,
      "partNumber":"217-3338",
      "vendor":"Vex",
      "desc":"48t Gear with 1.125\" Bearing Bore & VersaKeys",
      "customization":"",
      "unitsNeeded":8,
      "spareUnitsNeeded":0,
      "unitsInShop":0,
      "packagePrice":14.99,
      "unitsPerPackage":1,
      "notes":"",
      "dateAdded":null,
      "dateVerified":1455803965,
      "imgPath":"\/util\/img\/img-576.jpeg",
      "itemLink":"http:\/\/www.vexrobotics.com\/bearing-bore-gears.html",
      "ordered":0,
      "received":0,
      "receipts":null
    },
    575 : {
      "id":575,
      "bomID":bomID,
      "partNumber":"217-3342",
      "vendor":"Vex",
      "desc":"60t Gear with 1.125\" Bearing Bore & VersaKeys",
      "customization":"",
      "unitsNeeded":8,
      "spareUnitsNeeded":0,
      "unitsInShop":0,
      "packagePrice":19.99,
      "unitsPerPackage":1,
      "notes":"",
      "dateAdded":null,
      "dateVerified":1455803966,
      "imgPath":"\/util\/img\/img-575.jpg",
      "itemLink":"http:\/\/www.vexrobotics.com\/bearing-bore-gears.html",
      "ordered":0,
      "received":0,
      "receipts":null
    },
    542 : {
      "id":542,
      "bomID":bomID,
      "partNumber":"217-4006",
      "vendor":"Vex",
      "desc":"Flanged Bearing - 13.75mm (1\/2\" ThunderHex) x 1.125\" x 0.313\"",
      "customization":"",
      "unitsNeeded":22,
      "spareUnitsNeeded":0,
      "unitsInShop":0,
      "packagePrice":3.99,
      "unitsPerPackage":1,
      "notes":"",
      "dateAdded":null,
      "dateVerified":1454908839,
      "imgPath":"\/util\/img\/img-542.jpg",
      "itemLink":"http:\/\/www.vexrobotics.com\/bearings.html",
      "ordered":22,
      "received":22,
      "receipts":null
    },
    527 : {
      "id":527,
      "bomID":bomID,
      "partNumber":"217-2592",
      "vendor":"Vex",
      "desc":"VersaHub (1\/2\" Hex)",
      "customization":"",
      "unitsNeeded":4,
      "spareUnitsNeeded":4,
      "unitsInShop":0,
      "packagePrice":8.99,
      "unitsPerPackage":1,
      "notes":"",
      "dateAdded":null,
      "dateVerified":1454513477,
      "imgPath":"\/util\/img\/img-527.jpeg",
      "itemLink":"http:\/\/www.vexrobotics.com\/versahubs.html",
      "ordered":8,
      "received":0,
      "receipts":null
    },
    526 : {
      "id":526,
      "bomID":bomID,
      "partNumber":"217-3458",
      "vendor":"Vex",
      "desc":"Timing Belt (HTD 5mm) - 100T, 9mm Wide",
      "customization":"",
      "unitsNeeded":4,
      "spareUnitsNeeded":6,
      "unitsInShop":0,
      "packagePrice":7.49,
      "unitsPerPackage":1,
      "notes":"",
      "dateAdded":null,
      "dateVerified":1454513479,
      "imgPath":"\/util\/img\/img-526.jpg",
      "itemLink":"http:\/\/www.vexrobotics.com\/htdbelts9.html",
      "ordered":10,
      "received":0,
      "receipts":null
    },
    525 : {
      "id":525,
      "bomID":bomID,
      "partNumber":"217-3229",
      "vendor":"Vex",
      "desc":"Timing Pulley (HTD 5mm) - 30T, 9mm Double Flange, 1\/2\" Hex",
      "customization":"",
      "unitsNeeded":4,
      "spareUnitsNeeded":4,
      "unitsInShop":0,
      "packagePrice":12.99,
      "unitsPerPackage":1,
      "notes":"",
      "dateAdded":null,
      "dateVerified":1454513479,
      "imgPath":"\/util\/img\/img-525.jpg",
      "itemLink":"http:\/\/www.vexrobotics.com\/htdpulleys.html",
      "ordered":8,
      "received":0,
      "receipts":null
    },
    524 : {
      "id":524,
      "bomID":bomID,
      "partNumber":"217-3199",
      "vendor":"Vex",
      "desc":"VersaPulley Kit (HTD 5mm) - 42T, 18mm wide",
      "customization":"",
      "unitsNeeded":4,
      "spareUnitsNeeded":4,
      "unitsInShop":0,
      "packagePrice":4.99,
      "unitsPerPackage":1,
      "notes":"",
      "dateAdded":null,
      "dateVerified":1454513482,
      "imgPath":"\/util\/img\/img-524.jpg",
      "itemLink":"http:\/\/www.vexrobotics.com\/htdversapulley.html",
      "ordered":8,
      "received":0,
      "receipts":null
    },
    523 : {
      "id":523,
      "bomID":bomID,
      "partNumber":"217-2731",
      "vendor":"Vex",
      "desc":"Flanged Bearing - 0.500in x 1.125in x 0.313in",
      "customization":"",
      "unitsNeeded":20,
      "spareUnitsNeeded":26,
      "unitsInShop":0,
      "packagePrice":2.99,
      "unitsPerPackage":1,
      "notes":"",
      "dateAdded":null,
      "dateVerified":1454513484,
      "imgPath":"\/util\/img\/img-523.jpg",
      "itemLink":"http:\/\/www.vexrobotics.com\/bearings.html",
      "ordered":46,
      "received":0,
      "receipts":null
    },
    519 : {
      "id":519,
      "bomID":bomID,
      "partNumber":"92196A212",
      "vendor":"McMaster",
      "desc":"18-8 Stainless Steel Socket Head Cap Screw, 8-32 Thread, 2-3\/4\" Long",
      "customization":"",
      "unitsNeeded":36,
      "spareUnitsNeeded":40,
      "unitsInShop":0,
      "packagePrice":7.6,
      "unitsPerPackage":25,
      "notes":"Choose stainless steel screws when you need corrosion resistance. Length is measured from under the head.Inch screws have a Class 3A thread fit, a minimum tensile strength of 70,000 psi, and a minimum Rockwell hardness of B70.",
      "dateAdded":null,
      "dateVerified":1454513485,
      "imgPath":"\/util\/img\/img-519.png",
      "itemLink":"http:\/\/www.mcmaster.com\/#92196A212",
      "ordered":100,
      "received":0,
      "receipts":null
    },
    516 : {
      "id":516,
      "bomID":bomID,
      "partNumber":"am-2011",
      "vendor":"AndyMark",
      "desc":"Pneumatic fitting, straight, 1\/4\" tube, press-in, 1\/8\" NPT male",
      "customization":"",
      "unitsNeeded":4,
      "spareUnitsNeeded":8,
      "unitsInShop":0,
      "packagePrice":2,
      "unitsPerPackage":1,
      "notes":"",
      "dateAdded":null,
      "dateVerified":1454513487,
      "imgPath":"\/util\/img\/img-516.jpg",
      "itemLink":"http:\/\/www.andymark.com\/product-p\/am-2011.htm",
      "ordered":12,
      "received":0,
      "receipts":null
    },
    507 : {
      "id":507,
      "bomID":bomID,
      "partNumber":"98404A101",
      "vendor":"McMaster",
      "desc":"18-8 Stainless Steel Quick-Release Pin, 5\/32\" Diameter, 0.8\" Usable Length",
      "customization":"",
      "unitsNeeded":15,
      "spareUnitsNeeded":15,
      "unitsInShop":0,
      "packagePrice":1.76,
      "unitsPerPackage":1,
      "notes":"Also known as faspins, these pins have a ring grip. The ball springs inward during installation and pops out to lock the pin in place. The ball and spring are Type 316 stainless steel. The pin diameter equals the hole size. Shaft diameter tolerance is -0.003\". Shafts have a minimum Rockwell hardness of B85, except aluminum have a minimum Rockwell hardness of B56. Breaking strength is measured as single shear, which is the force required to break a pin into two pieces.18-8 stainless steel pins are more corrosion resistant than zinc-plated pins and may be mildly magnetic.",
      "dateAdded":null,
      "dateVerified":1454098737,
      "imgPath":"\/util\/img\/img-507.png",
      "itemLink":"http:\/\/www.mcmaster.com\/#98404A101",
      "ordered":30,
      "received":0,
      "receipts":null
    },
    505 : {
      "id":505,
      "bomID":bomID,
      "partNumber":"97526A140",
      "vendor":"McMaster",
      "desc":"Choose-A-Color Blind Rivet, Domed, 3\/16\" Diameter, .126\"-.25\" Material Thickness",
      "customization":"",
      "unitsNeeded":300,
      "spareUnitsNeeded":400,
      "unitsInShop":100,
      "packagePrice":8.53,
      "unitsPerPackage":100,
      "notes":"Select a color that makes your rivets stand out or blend in. Rivets and mandrels are aluminum, which is corrosion resistant and nonmagnetic. They meet IFI 114 (Industrial Fasteners Institute) standards.",
      "dateAdded":null,
      "dateVerified":1454098735,
      "imgPath":"\/util\/img\/img-505.png",
      "itemLink":"http:\/\/www.mcmaster.com\/#97526A140",
      "ordered":600,
      "received":0,
      "receipts":null
    },
    503 : {
      "id":503,
      "bomID":bomID,
      "partNumber":"am-2023",
      "vendor":"AndyMark",
      "desc":"Ball Valve, 1\/4\" NPT Male x Female, Lever Handle, Chrome Plated",
      "customization":"",
      "unitsNeeded":1,
      "spareUnitsNeeded":1,
      "unitsInShop":1,
      "packagePrice":7.5,
      "unitsPerPackage":1,
      "notes":"",
      "dateAdded":null,
      "dateVerified":1454513489,
      "imgPath":"\/util\/img\/img-503.jpg",
      "itemLink":"http:\/\/www.andymark.com\/product-p\/am-2023.htm",
      "ordered":1,
      "received":0,
      "receipts":null
    },
    502 : {
      "id":502,
      "bomID":bomID,
      "partNumber":"am-3147",
      "vendor":"AndyMark",
      "desc":"Pressure Gauge, 1\/8\" NPT, 0-160 PSI",
      "customization":"",
      "unitsNeeded":2,
      "spareUnitsNeeded":3,
      "unitsInShop":4,
      "packagePrice":12.5,
      "unitsPerPackage":1,
      "notes":"",
      "dateAdded":null,
      "dateVerified":1454513490,
      "imgPath":"\/util\/img\/img-502.jpg",
      "itemLink":"http:\/\/www.andymark.com\/product-p\/am-3147.htm",
      "ordered":1,
      "received":0,
      "receipts":null
    },
    501 : {
      "id":501,
      "bomID":bomID,
      "partNumber":"am-2015",
      "vendor":"AndyMark",
      "desc":"Pneumatic fitting, union tee, 1\/4\" tube",
      "customization":"",
      "unitsNeeded":10,
      "spareUnitsNeeded":10,
      "unitsInShop":16,
      "packagePrice":3,
      "unitsPerPackage":1,
      "notes":"",
      "dateAdded":null,
      "dateVerified":1454513493,
      "imgPath":"\/util\/img\/img-501.jpg",
      "itemLink":"http:\/\/www.andymark.com\/product-p\/am-2015.htm",
      "ordered":4,
      "received":0,
      "receipts":null
    },
    500 : {
      "id":500,
      "bomID":bomID,
      "partNumber":"91251A018",
      "vendor":"McMaster",
      "desc":"Black-Oxide Alloy Steel Socket Head Cap Screw, 1\/2\"-20 Thread, 1-3\/4\" Length",
      "customization":"",
      "unitsNeeded":0,
      "spareUnitsNeeded":4,
      "unitsInShop":0,
      "packagePrice":5.79,
      "unitsPerPackage":5,
      "notes":"The standard among high-strength fasteners, these screws are stronger than Grade 8 steel screws. They have a minimum tensile strength of 170,000 psi. and a minimum Rockwell hardness of C37. Length is measured from under the head.Inch screws have a Class 3A thread fit. They meet ASTM A574.Black Oxide\u2014Screws have been heat-treated for hardness, which results in a dark surface color.",
      "dateAdded":null,
      "dateVerified":1454098731,
      "imgPath":"\/util\/img\/img-500.png",
      "itemLink":"http:\/\/www.mcmaster.com\/#91251A018",
      "ordered":5,
      "received":0,
      "receipts":null
    },
    499 : {
      "id":499,
      "bomID":bomID,
      "partNumber":"am-2010",
      "vendor":"AndyMark",
      "desc":"Pneumatic fitting, straight, 1\/4\" tube, press-in, 1\/4\" NPT male",
      "customization":"",
      "unitsNeeded":4,
      "spareUnitsNeeded":8,
      "unitsInShop":0,
      "packagePrice":2,
      "unitsPerPackage":1,
      "notes":"",
      "dateAdded":null,
      "dateVerified":1453835192,
      "imgPath":"\/util\/img\/img-499.jpg",
      "itemLink":"http:\/\/www.andymark.com\/product-p\/am-2010.htm",
      "ordered":12,
      "received":0,
      "receipts":null
    },
    474 : {
      "id":474,
      "bomID":bomID,
      "partNumber":"91251a020",
      "vendor":"McMaster",
      "desc":"Black-Oxide Alloy Steel Socket Head Cap Screw, 1\/2\"-20 Thread, 2\" Length",
      "customization":"",
      "unitsNeeded":2,
      "spareUnitsNeeded":2,
      "unitsInShop":0,
      "packagePrice":6.55,
      "unitsPerPackage":5,
      "notes":"The standard among high-strength fasteners, these screws are stronger than Grade 8 steel screws. They have a minimum tensile strength of 170,000 psi. and a minimum Rockwell hardness of C37. Length is measured from under the head.Inch screws have a Class 3A thread fit. They meet ASTM A574.Black Oxide\u2014Screws have been heat-treated for hardness, which results in a dark surface color.",
      "dateAdded":null,
      "dateVerified":1453670693,
      "imgPath":"\/util\/img\/img-474.png",
      "itemLink":"http:\/\/www.mcmaster.com\/#91251a020",
      "ordered":5,
      "received":0,
      "receipts":null
    },
    473 : {
      "id":473,
      "bomID":bomID,
      "partNumber":"90566a030",
      "vendor":"McMaster",
      "desc":"Low-Strength Steel Thin Nylon-Insert Locknut, Zinc Plated, 5\/16\"-18 Thread Size, 1\/2\" Wide, 1\/4\" High",
      "customization":"",
      "unitsNeeded":16,
      "spareUnitsNeeded":16,
      "unitsInShop":0,
      "packagePrice":4.39,
      "unitsPerPackage":100,
      "notes":"Thinner than standard nylon-insert locknuts, these nuts can be used in tight spaces where clearance is limited. The nylon-insert grips threads to resist loosening without damaging threads. These nuts are reusable, but their holding power lessens with each use. Nylon absorbs moisture, which can cause the insert to become brittle over time in wet environments. Maximum temperature of the insert is 220\u00b0 F. Thread fit is Class 2B, unless noted.",
      "dateAdded":null,
      "dateVerified":1453670693,
      "imgPath":"\/util\/img\/img-473.png",
      "itemLink":"http:\/\/www.mcmaster.com\/#90566a030",
      "ordered":100,
      "received":0,
      "receipts":null
    },
    448 : {
      "id":448,
      "bomID":bomID,
      "partNumber":"217-3200",
      "vendor":"Vex",
      "desc":"VersaPulley Kit (HTD 5mm) - 60T, 18mm wide",
      "customization":"",
      "unitsNeeded":6,
      "spareUnitsNeeded":8,
      "unitsInShop":0,
      "packagePrice":5.99,
      "unitsPerPackage":1,
      "notes":"",
      "dateAdded":null,
      "dateVerified":1453670693,
      "imgPath":"\/util\/img\/img-448.jpg",
      "itemLink":"http:\/\/www.vexrobotics.com\/htdversapulley.html",
      "ordered":14,
      "received":0,
      "receipts":null
    },
    447 : {
      "id":447,
      "bomID":bomID,
      "partNumber":"217-3199",
      "vendor":"Vex",
      "desc":"VersaPulley Kit (HTD 5mm) - 42T, 18mm wide",
      "customization":"",
      "unitsNeeded":4,
      "spareUnitsNeeded":6,
      "unitsInShop":0,
      "packagePrice":4.99,
      "unitsPerPackage":1,
      "notes":"",
      "dateAdded":null,
      "dateVerified":1453670693,
      "imgPath":"\/util\/img\/img-447.jpg",
      "itemLink":"http:\/\/www.vexrobotics.com\/htdversapulley.html",
      "ordered":10,
      "received":0,
      "receipts":null
    },
    446 : {
      "id":446,
      "bomID":bomID,
      "partNumber":"89965K354",
      "vendor":"McMaster",
      "desc":"Multipurpose Aluminum Tubing 1\/2\" OD, .384\" ID, .058\" Wall Thickness",
      "customization":"6",
      "unitsNeeded":1,
      "spareUnitsNeeded":2,
      "unitsInShop":0,
      "packagePrice":22.2,
      "unitsPerPackage":1,
      "notes":"",
      "dateAdded":null,
      "dateVerified":1453670693,
      "imgPath":"\/util\/img\/img-446.png",
      "itemLink":"http:\/\/www.mcmaster.com\/#89965k354\/=10qnwet",
      "ordered":3,
      "received":0,
      "receipts":null
    },
    444 : {
      "id":444,
      "bomID":bomID,
      "partNumber":"217-2591",
      "vendor":"Vex",
      "desc":"VersaHub (1.125\" Bearing Pilot, 1\/2\" Thick, w\/ Plate Sprocket Mount)",
      "customization":"",
      "unitsNeeded":4,
      "spareUnitsNeeded":6,
      "unitsInShop":0,
      "packagePrice":2.99,
      "unitsPerPackage":1,
      "notes":"",
      "dateAdded":null,
      "dateVerified":1453670693,
      "imgPath":"\/util\/img\/img-444.jpeg",
      "itemLink":"http:\/\/www.vexrobotics.com\/versahubs.html",
      "ordered":10,
      "received":0,
      "receipts":null
    },
    443 : {
      "id":443,
      "bomID":bomID,
      "partNumber":"am-0207a",
      "vendor":"AndyMark",
      "desc":"250 Sprocket and Pulley Spacer",
      "customization":"",
      "unitsNeeded":6,
      "spareUnitsNeeded":8,
      "unitsInShop":0,
      "packagePrice":4,
      "unitsPerPackage":1,
      "notes":"",
      "dateAdded":null,
      "dateVerified":1453670693,
      "imgPath":"\/util\/img\/img-443.jpg",
      "itemLink":"http:\/\/www.andymark.com\/product-p\/am-0207a.htm",
      "ordered":14,
      "received":0,
      "receipts":null
    }
  }

}

export default function getBomItems(params){
  return _getBomItems(params.bomID);
}
